language: php

sudo: true

php:
  - 7.2

install:
  - travis_retry composer install --no-interaction --no-ansi --no-progress --no-suggest --prefer-source

script:
  - sudo vendor/bin/phpunit -c phpunit.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
