language: php

sudo: false

php:
  - 7.2

install:
  - travis_retry composer install --no-interaction --no-ansi --no-progress --no-suggest --prefer-source

script:
#  - mkdir -p $TMPDIR/donbidon/tests/lib-fs
#  - printenv
#  - set
  - phpunit -dsys_temp_dir="$TRAVIS_TMPDIR" -c phpunit.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
